services:
  mongodb:
    image: mongo:latest
    container_name: tip_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: tip_elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: tip_kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  enforcer:
    build:
      context: .
      dockerfile: Dockerfile.enforcer
    container_name: tip_enforcer
    depends_on:
      - mongodb
    cap_add:
      - NET_ADMIN

volumes:
  mongo_data:
  es_data: